Add 'online' column for Country
ioi-2022/translation pull request #29
Opened 2022-04-09 07:08 UTC by Si-plus-plus

- Add `online` column with Boolean data type for Country table
- Add prefilled `online` column for countries2019.csv

2022-04-09 07:37 UTC, fushar approved these changes

2022-04-09 09:24 UTC, fushar requested changes

2022-04-09 09:24 UTC, fushar commented on data/countries2019.csv
> +,0
Looks like this is not intended

2022-04-09 11:29 UTC, raisfathin requested changes
I think there should be a migration file in trans/migrations. That needs to be committed as well. Did `manage.py makemigrations` not generate any?

2022-04-10 01:46 UTC, Si-plus-plus commented on data/countries2019.csv
> +,0
missed that, fixed.

2022-04-10 01:54 UTC, Si-plus-plus commented
> I think there should be a migration file in trans/migrations. That needs to be committed as well. Did `manage.py makemigrations` not generate any?

![image](https://user-images.githubusercontent.com/56646525/162597733-1fd8dc91-b1eb-4324-944a-269a1e29cddf.png)

It should have generated one, but it didn't. The bottommost file inside the trans/migrations folder was created last year, while the rest was from 2017-2018.

2022-04-10 07:29 UTC, fushar commented
> It should have generated one, but it didn't. 

I just tried, it did generate a new migration file:

```
root@08b05b9ed9ed:/usr/src/app# python3 manage.py makemigrations
(0.003)
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
(0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Migrations for 'trans':
  trans/migrations/0018_country_online.py
    - Add field online to country
```

The file was created inside the docker container, so you need to scp it out, or just copy-paste the content :)

2022-04-10 13:24 UTC, Si-plus-plus commented
> > It should have generated one, but it didn't.
> 
> I just tried, it did generate a new migration file:
> 
> ```
> root@08b05b9ed9ed:/usr/src/app# python3 manage.py makemigrations
> (0.003)
>             SELECT c.relname, c.relkind
>             FROM pg_catalog.pg_class c
>             LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
>             WHERE c.relkind IN ('r', 'v')
>                 AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
>                 AND pg_catalog.pg_table_is_visible(c.oid); args=None
> (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
> Migrations for 'trans':
>   trans/migrations/0018_country_online.py
>     - Add field online to country
> ```
> 
> The file was created inside the docker container, so you need to scp it out, or just copy-paste the content :)

Thanks for pointing it out. I wouldn't have realized it otherwise

2022-04-10 13:48 UTC, raisfathin approved these changes

2022-04-10 13:51 UTC, fushar approved these changes

2022-04-10 13:52 UTC, merged